// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xqngrmlgqagzldqdwolu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhxbmdybWxncWFnemxkcWR3b2x1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNTAyNzksImV4cCI6MjA2NjcyNjI3OX0.8e5pfRWRk3sZHKmFtug-RuagvlR7JXIkea1DlFRBlxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);